import React from 'react';

interface PrintFooterProps {
  auditId?: string;
}

export function PrintFooter({ auditId = 'SYS-AUTO' }: PrintFooterProps) {
  return (
    <div className="hidden print:block fixed bottom-0 left-0 right-0 border-t border-border pt-2 text-center text-[10px] text-muted-foreground bg-background">
      <p suppressHydrationWarning>Generated by Auralis Orbital Mission Control — Audit ID: {auditId}-{Math.floor(Math.random() * 10000)}</p>
      <p>This report contains flight-critical conjunction telemetry and space situational awareness data.</p>
    </div>
  );
}
